name: avarium_avatar_creator
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # core
  go_router: ^14.2.7
  logger: any
  easy_debounce: ^2.0.3
  audioplayers: ^6.1.0
  url_launcher: ^6.3.0
  flutter_webrtc: ^0.11.7
  web_socket_channel: ^3.0.1

  # ui
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.6
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  gradient_borders: ^1.0.1
  blur: ^4.0.0
  flutter_glow: ^0.3.2
  animated_toggle_switch: ^0.8.3
  flutter_colorpicker: ^1.1.0
  video_player: ^2.9.1
  awesome_dialog: ^3.2.1

  # data
  json_annotation: ^4.8.1
  dio: ^5.3.2
  retrofit: ^4.0.1
  flutter_secure_storage: ^9.0.0
  flutter_riverpod: ^2.3.10

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/fonts/
    - assets/images/
    - assets/videos/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
          style: normal
